version: "3.7"
services:
  backspace:
    container_name: backspace-container
    user: '1000'
    ports:
      - 80:3000
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        user: backspace
        uid: 1000
    # volumes:
    #   - ./:/backspace
    networks:
      - backspace

  mysql:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: backspace
    volumes:
      - mysql-data:/docker-entrypoint-initdb.d
    networks:
      - backspace

volumes:
  mysql-data:
    driver: local

networks:
  backspace:
    driver: bridge